### ISSUE TITLE
Question about formulas in the paper.

### ISSUE THREAD

**Issue by zhenshan0127** [edexheim/DepthCov#2]
Hello,

Thanks for this amazing work. I am confused about the formulas (10) and (11) in the paper. What are the definitions of the parameters, $K_{fn}$ and $K_{nn}$? And, what's the meaning of $m$ in (10)?

Also, I cannot find their corresponding parameters in the souce code. Could you please provides some correspondence between the parameters in the paper and the symbols in the source code?

Thank for your time and patience.

**Comment by edexheim** [comment]
Hello,

Thank you for your interest.  The subscript $\mathrm{f}$ is referring to all pixels in the domain, so a flat version of height x width.  The subscript $\mathrm{n}$ refers to the set of observations you have.  The shapes are then $K_{\mathrm{fn}} \in \mathbb{R}^{HW \times N}$ and $K_{ \mathrm{nn}} \in \mathbb{R}^{N \times N}$.  The entries in each of these matrices are filled in by the corresponding covariance between pixels, so $K_{\mathrm{nn}}$ contains all the covariances between pixels with observations, while $K_{\mathrm{fn}}$ is the cross covariance between all pixels and pixels with observations.

The parameter $m$ is a scalar mean log-depth originally mentioned in Section 3.1 and (2).  This variable gives flexibility in modeling scale for example.

I use the variables in different places throughout the code, but for conditioning with known observations, these matrices show up here (train is referring to $\mathrm{n}$ since those are the points we condition on, while test refers where we evaluate or $\mathrm{f}$): 

https://github.com/edexheim/DepthCov/blob/f42f0d0019b057b48fb4dfcebe3b285e7d64513f/depth_cov/core/NonstationaryGpModule.py#L96

Let me know if you have any more questions.
Eric

**Comment by zhenshan0127** [comment]
Hello Eric,

Thank you for your reply!
